all_paths_num = 217
all_dataset_num = 133
img_datas = [
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/AMOS2022',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/ATM2022',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/AbdomenCT1K',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/BTCV',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/BTCV_Cervix',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/CAD_PE',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/CHAOS_Task_4',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/COVID-19-20',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/COVID19CTscans',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/CTPelvic1k',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/CTSpine1K_Full',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/CT_ORG',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/Chest_CT_Scans_with_COVID-19',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/FLARE21',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/FLARE22',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/FUMPE',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/HaN-Seg',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/HeadandNeckAutoSegmentationChallenge',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/ISLES2018',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/Instance22',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/KiPA22',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/KiTS',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/KiTS2021',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/LITS',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/LNDb',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/LUNA16',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/MMWHS',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/MSD_Colon',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/MSD_HepaticVessel',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/MSD_Liver',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/MSD_Lung',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/MSD_Pancreas',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/MSD_Spleen',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/Parse22',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/Pelvis_v1_lianxin',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/RibFrac2020',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/SLIVER07',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/STACOM_SLAWT',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/SegThor',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/StructSeg2019_subtask1',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/StructSeg2019_subtask2',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/StructSeg2019_subtask3',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/StructSeg2019_subtask4',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/Totalsegmentator_dataset',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/VESSEL2012',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/VerSe19',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/VerSe20',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/WORD',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/abdomen105cases_lianxin_overlap_to_bg',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/autoPET', 很多0label
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/autoPET_cgy',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/autoPET_ori', 很多0label
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/autoPET_ori_cgy',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/brachial_plexus',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/brain_CTA_fromSJTU',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset1',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset10',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset11',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset12',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset13',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset14',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset15',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset16',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset17',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset18',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset19',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset1_cgy',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset2',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset20',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset21',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset22',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset2_cgy',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset3',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset4',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset5',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset6',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset7',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset8',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/dataset9',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct/orCaScore',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct_cbf/ISLES2018',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct_cbv/ISLES2018',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct_mtt/ISLES2018',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/ct_tmax/ISLES2018',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_adc/ISLES2016',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_adc/ISLES2017',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_adc/ISLES2022',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_adc/MSD_Prostate',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_c0/Myops2020',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_cbf/ISLES_SPES',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_cbv/ISLES_SPES',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_cmr/CMRxMotions',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_de/Myops2020',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_dp/MSSEG2016',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_dwi/ISLES2022',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_dwi/ISLES_SISS',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_dwi/ISLES_SPES',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/BraTS2013',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/BraTS2015',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/BraTS2018',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/BraTS2019',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/BraTS2020',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/BraTS2021',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/BrainTumour',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/ISLES_SISS',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/LongitudinalMultipleSclerosisLesionSegmentation',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/MESSEG', 很多0label的
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/MSSEG2016',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/MSseg08',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/VALDO_Task1',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/VALDO_Task3',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_flair/WMH',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_gado/MSSEG2016',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_hbv/picai_baseline', 很多label0的
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_hbv/picai_semi',  很多label0的
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_lge/ASC18',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_lge/LAScarQS22_task1',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_lge/LAScarQS22_task2',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_mprage/LongitudinalMultipleSclerosisLesionSegmentation',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_mtt/ISLES2016',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_mtt/ISLES2017',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_pd/LongitudinalMultipleSclerosisLesionSegmentation',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_rcbf/ISLES2016',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_rcbf/ISLES2017',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_rcbv/ISLES2016',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_rcbv/ISLES2017',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/BraTS2013',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/BraTS2015',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/BraTS2018',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/BraTS2019',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/BraTS2020',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/BraTS2021',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/Brain_PTM',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/ISLES_SISS',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/MRBrain18_new',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/MRBrainS13',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/MSSEG2016',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/MSseg08',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/WMH',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/iSeg2017',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1/iseg2019',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1c/BraTS2013',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1c/BraTS2015',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1c/ISLES_SPES',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1ce/BraTS2018',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1ce/BraTS2019',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1ce/BraTS2020',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1ce/BraTS2021',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1ce/CrossMoDA21',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1ce/CrossMoDA22',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1gd/BrainTumour',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1ir/MRBrain18_new',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1ir/MRBrainS13',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1w/ATLAS_2',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1w/BrainTumour',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1w/CHAOS_Task_4',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1w/HaN-Seg',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1w/VALDO_Task1',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1w/VALDO_Task2',很多label0，且值很小
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t1w/VALDO_Task3',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/BraTS2013',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/BraTS2015',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/BraTS2018',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/BraTS2019',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/BraTS2020',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/BraTS2021',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/ISLES_SISS',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/ISLES_SPES',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/LongitudinalMultipleSclerosisLesionSegmentation',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/MSD_Prostate',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/MSSEG2016',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/MSseg08',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/Myops2020',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/iSeg2017',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2/iseg2019',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2flair/MRBrain18_new',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2flair/MRBrainS13',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2hr/CrossMoDA21',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2hr/CrossMoDA22',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2s/VALDO_Task2',很多label0，且值很小
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2w/BrainTumour',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2w/CHAOS_Task_4',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2w/FeTA',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2w/FeTA2022_all',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2w/Promise09',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2w/Prostate_MRI_Segmentation_Dataset',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2w/VALDO_Task1',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2w/VALDO_Task2', 很多label0，且值很小
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2w/VALDO_Task3',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2w/picai_baseline', 很多label0的
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_t2w/picai_semi',  很多label0的
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_tmax/ISLES2016',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_tmax/ISLES2017',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_tmax/ISLES_SPES',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_ttp/ISLES2016',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_ttp/ISLES2017',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_ttp/ISLES_SPES',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/ACDC',
# 什么sform不对什么的
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/AMOS2022',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/CAUSE07',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/COSMOS2022',
# 有问题，显示什么pid 什么bus
# DataLoader worker (pid 2218114) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit
# Image data has type int64, which may cause incompatibilities with other tools. To use this type, pass an explicit header or dtype argument to Nifti1Image().
# torch.Size([1, 432, 432, 432])
# torch.Size([1, 432, 432, 432])
# /cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/COSMOS2022/imagesTr/case_0007.nii.gz
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/EMIDEC',
# 什么sform不对什么的
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/Heart_Seg_MRI',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/MMWHS',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/MSD_Heart',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/MSD_Hippocampus',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/PROMISE12',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/STACOM_SLAWT',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/abdomen_tissue_fromSJTU',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/cSeg-2022',
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/hvsmr_2016',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/mnms', label几乎全是0，只有一两个sum一两百的
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/mr_unknown/mnms2',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/pet/autoPET', lession，很多label0的
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/pet/autoPET_cgy',
# '/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/pet/autoPET_ori',  lession，很多label0的
'/cpfs01/shared/gmai/medical_preprocessed/3d/semantic_seg/pet/autoPET_ori_cgy',
]
all_datasets = [
# 'ACDC',
'AMOS2022',
'ASC18',
'ATLAS_2',
'ATM2022',
'AbdomenCT1K',
'BTCV',
'BTCV_Cervix',
'BraTS2013',
'BraTS2015',
'BraTS2018',
'BraTS2019',
'BraTS2020',
'BraTS2021',
'BrainTumour',
'Brain_PTM',
'CAD_PE',
'CAUSE07',
'CHAOS_Task_4',
'CMRxMotions',
# 'COSMOS2022',
'COVID-19-20',
'COVID19CTscans',
'CTPelvic1k',
'CTSpine1K_Full',
'CT_ORG',
'Chest_CT_Scans_with_COVID-19',
'CrossMoDA21',
'CrossMoDA22',
# 'EMIDEC',
'FLARE21',
'FLARE22',
'FUMPE',
'FeTA',
'FeTA2022_all',
'HaN-Seg',
'HeadandNeckAutoSegmentationChallenge',
'Heart_Seg_MRI',
'ISLES2016',
'ISLES2017',
'ISLES2018',
'ISLES2022',
'ISLES_SISS',
'ISLES_SPES',
'Instance22',
'KiPA22',
'KiTS',
'KiTS2021',
'LAScarQS22_task1',
'LAScarQS22_task2',
'LITS',
'LNDb',
'LUNA16',
'LongitudinalMultipleSclerosisLesionSegmentation',
# 'MESSEG',
'MMWHS',
'MRBrain18_new',
'MRBrainS13',
'MSD_Colon',
'MSD_Heart',
'MSD_HepaticVessel',
'MSD_Hippocampus',
'MSD_Liver',
'MSD_Lung',
'MSD_Pancreas',
'MSD_Prostate',
'MSD_Spleen',
'MSSEG2016',
'MSseg08',
'Myops2020',
'PROMISE12',
'Parse22',
'Pelvis_v1_lianxin',
'Promise09',
'Prostate_MRI_Segmentation_Dataset',
'RibFrac2020',
'SLIVER07',
'STACOM_SLAWT',
'SegThor',
'StructSeg2019_subtask1',
'StructSeg2019_subtask2',
'StructSeg2019_subtask3',
'StructSeg2019_subtask4',
'Totalsegmentator_dataset',
'VALDO_Task1',
# 'VALDO_Task2',
'VALDO_Task3',
'VESSEL2012',
'VerSe19',
'VerSe20',
'WMH',
'WORD',
'abdomen105cases_lianxin_overlap_to_bg',
'abdomen_tissue_fromSJTU',
# 'autoPET',
'autoPET_cgy',
# 'autoPET_ori',
'autoPET_ori_cgy',
'brachial_plexus',
'brain_CTA_fromSJTU',
'cSeg-2022',
'dataset1',
'dataset10',
'dataset11',
'dataset12',
'dataset13',
'dataset14',
'dataset15',
'dataset16',
'dataset17',
'dataset18',
'dataset19',
'dataset1_cgy',
'dataset2',
'dataset20',
'dataset21',
'dataset22',
'dataset2_cgy',
'dataset3',
'dataset4',
'dataset5',
'dataset6',
'dataset7',
'dataset8',
'dataset9',
'hvsmr_2016',
'iSeg2017',
'iseg2019',
# 'mnms',
'mnms2',
'orCaScore',
# 'picai_baseline',
# 'picai_semi',
]
